### ISSUE TITLE
Unnamed struct members are skipped 

### ISSUE THREAD

**Issue by athre0z** [JuliaInterop/Clang.jl#233]
Unnamed nested structures/unions are currently skipped.

Given
```C
struct Meow {
    int blah;
    union {
        float either1;
        int either2;
    };
    float moo;
};
```
the lib generates the following Julia code:
```Julia
struct Meow
    blah::Cint
    moo::Cfloat
end
```

The problem goes away when giving the member a name. Maybe generating a member called something along the lines of "anon_0" for these unnamed nested items would be best?

**Comment by Gnimuc** [comment]
It's not easy to support this C11 feature using bare Julia struct since Julia's struct doesn't have this kinda feature. However, as Julia allows us to overload `Base.getproperty`, we could emulate this behavior. You could take [this snippet](https://github.com/JuliaMultimedia/CSFML.jl/blob/812f21224d683f4119b02c456dda47d4d0a4a471/src/Window/window_common.jl#L272-L314) as an example on how to emulate a C union in Julia. 

In this way, non-canonical C structs/unions should be auto-generated as a struct with a single data byte field (e.g. `struct Foo; data::NTuple{N,UInt8}); end`) where the size `N` can be computed from Clang AST. The corresponding `Base.getproperty` function can also be generated basically in the same pattern. I guess `__attribute__` identifiers can also be supported in the same way. 

To support this, `wrap_c.jl` needs to be refactored, but I currently don't have time to do this, so if your code only have several C11 structures, the "best practice" for now is to overload `Base.getproperty` manually.

**Comment by athre0z** [comment]
Thank you for the quick & detailed response! Overloading `getproperty` is what I currently do. Auto-generating such methods in the long term sounds great in general -- this way, regular unions would become a lot nicer as well!

Since just skipping the member results in misaligned fields afterwards, for now, maybe adding a warning when encountering such unnamed fields would be a good thing -- or just generating a name for the field? In my case it was rather obvious, but other people might be less fortunate, not realizing why their struct fields are misaligned after a skipped field.

**Comment by Gnimuc** [comment]
Hi @athre0z, could you share a link to your wrapper repo? I'd like to give #278 a test. Any suggestions on how to overload `Base.getproperty` would be highly appreciated.

**Comment by athre0z** [comment]
Hi @Gnimuc! Unfortunately I don't remember where exactly I used that and I'm not even sure if this ever ended up in a commit, sorry! I think what I did was simply performing an if on the symbol, then have an `unsafe_load` for each field with a hard-coded struct offset.

**Comment by cdsousa** [comment]
Hi, I've just tried master branch with the code presented by the OP and it fails with ```ERROR: There is no definition for Meow's field: 's type: [`union Meow::(anonymous at ......```
Is that expected?

**Comment by Gnimuc** [comment]
Which version are you using？

令和4年8月24日(水) 2:01 Cristóvão Duarte Sousa ***@***.***>:

**Comment by cdsousa** [comment]
I've tried it with Clang 0.16.0 and the current master branch, within Julia 1.8.

**Comment by Gnimuc** [comment]
Could you share some info about the C header?
