### ISSUE TITLE
Not emitting definition for INT8_MAX (from stdint)

### ISSUE THREAD

**Issue by Octogonapus** [JuliaInterop/Clang.jl#446]
I'm wrapping the AWS CRT packages and I have encountered some weird behavior. This C code:

```c
// stdint.h is included indirectly through a number of headers which are also passed to Clang.jl
#define AWS_EVENT_STREAM_HEADER_NAME_LEN_MAX (INT8_MAX)
```

causes this wrapper to be generated:

```julia
const AWS_EVENT_STREAM_HEADER_NAME_LEN_MAX = INT8_MAX
```

There's no definition for `INT8_MAX` in the generated code. It would be great if Clang.jl could emit:

```julia
const AWS_EVENT_STREAM_HEADER_NAME_LEN_MAX = 127
```

or at least:

```julia
const INT8_MAX = 127
const AWS_EVENT_STREAM_HEADER_NAME_LEN_MAX = INT8_MAX
```

Is Clang.jl expected to fail in this case, or did I misconfigure something?

Clang.jl v0.17.6
Julia v1.9.3

**Comment by Gnimuc** [comment]
Yes. It's technically impossible to do this because macro expanding is handled by the preprocessor, before the AST is created, and we can only extract info from the AST. The identifier `INT8_MAX` could be anything, it's legal to undef it and define it again. So, unless we implement a full-featured C preprocessor in Julia, it's hard to do it without any mistakes.

However, the best practice is much simpler. We can add `const INT8_MAX = typemax(Int8)` to [the prologue file](https://github.com/JuliaInterop/Clang.jl/blob/master/gen/prologue.jl) and do it once for all.

I know the ultimate solution is something like Rust's https://github.com/rust-lang/libc. But in practice, as Julia is niche at the moment, we really don't have that manpower. ;)

**Comment by Octogonapus** [comment]
Fair enough
